fix badges statistics saving and calculating percentageOfUsersInProgress
ice-blockchain/santa pull request #13
Opened 2023-03-14 15:45 UTC by ice-cronus

2023-03-14 16:03 UTC, ice-ares commented on application.yaml
> +      - name: achieved-badges
u have 1 more application.yaml to update

2023-03-14 16:05 UTC, ice-ares commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
remove allTypes []Type and get it internally

2023-03-14 16:05 UTC, ice-ares commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
calculateUnachievedPercentages

2023-03-14 16:08 UTC, ice-ares commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
also, add some unit tests for this, close to 100% coverage

Most important test case: some users didn't achieve anything, some users achieved everything, the rest is randomly achieved

2023-03-14 16:09 UTC, ice-ares commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
also,  the float64 is a percentage : 23,55%, not 0,2355

2023-03-14 16:14 UTC, ice-ares commented on badges/get_badges.go
> +		if usersToAchieveCurrBadgeType >= totalUsers {
don't think this is correct. I'd iterate from tail to head.

Cuz if you achieved badge 3, you also have achieved 1 & 2, and you shouldn't include it in the calculation for 1 & 2 & 3

2023-03-15 08:19 UTC, ice-cronus commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
> also, the float64 is a percentage : 23,55%, not 0,2355
Do we need to keep rounding logic on BE or FE will format is as required? 2 digits after point?

2023-03-15 08:23 UTC, ice-cronus commented on badges/get_badges.go
> +		if usersToAchieveCurrBadgeType >= totalUsers {
That was my original idea to iterate from the tail, but then I figured out that in most cases count of users in progress with a badge is the count of users who owns the previous one. But I will think again about iterating from the end, may be it would be some less complexity (not sure if we should worry about it for about 25 records)

2023-03-15 08:26 UTC, ice-ares commented on badges/get_badges.go
> +func (*repository) calculateUnachievedPercentage(allTypes []Type, res []*statistics) map[Type]float64 {
don't bother with rounding

2023-03-16 10:05 UTC, ice-ares reviewed
The business is: 

First badge percentage = users who didnt achieve any badge

2nd badge percentage = users who achieved 1st badge and didn't achieve 2nd badge

3rd badge percentage = users who achieved 2nd badge and didn't achieve 3rd badge - users who achieved 1st badge - users who achieved no badges

...

2023-03-16 10:43 UTC, ice-cronus commented on badges/get_badges.go
> +	if totalAchievedBy > totalUsers || totalAchievedBy == 0 {
to get 100% for first badge if no one have no badges, other wise it would be zero cuz 0(totalAchievedBy)-0(for badge1)/total = 0

2023-03-17 10:00 UTC, ice-ares requested changes

2023-03-17 10:00 UTC, ice-ares commented on badges/get_badges.go
> +	for ind, currentBadgeType := range allTypes {
Pls reverse iterate over this, cuz this is not accurate

2023-03-17 10:00 UTC, ice-ares commented on badges/get_badges_test.go
> +				Social6Type:  0,
Thats not possible. Every other one after this has to be 0

2023-03-17 10:31 UTC, ice-ares submitted a review, later dismissed

2023-03-17 13:23 UTC, ice-nestor approved these changes

2023-03-17 14:39 UTC, merged