Unit tests for levels and roles
ice-blockchain/santa pull request #14
Opened 2023-03-20 11:53 UTC by ice-nestor

In this pr, unit tests are added for levels and roles.

2023-03-20 12:52 UTC, ice-ares commented on cmd/santa-sleigh/santa_sleigh.go
> +	// s.tasksProcessor = tasks.StartProcessor(ctx, cancel)
rollback

2023-03-20 12:54 UTC, ice-ares commented on levels-and-roles/completed_levels_test.go
> +			require.Equal(t, tt.expected, got)
equal values

2023-03-21 09:04 UTC, ice-nestor commented on levels-and-roles/completed_levels.go
> +			continue
yeah, but there is no need to specify label

2023-03-21 10:06 UTC, ice-cronus requested changes

2023-03-21 10:06 UTC, ice-cronus commented on levels-and-roles/completed_levels_test.go
> +	}
create complex test with achieving levels from different groups as well

2023-03-21 10:06 UTC, ice-cronus commented on levels-and-roles/completed_levels_test.go
> +	}
also achieving next level (when user has level1 and passed requirments for level2 in the same group) is missing too

2023-03-21 10:06 UTC, ice-cronus commented on levels-and-roles/completed_levels_test.go
> +	}
also when users achieves multiple levels at once

2023-03-21 11:24 UTC, ice-myles requested changes

2023-03-21 11:24 UTC, ice-myles commented on levels-and-roles/levels_and_roles_test.go
> +		},
No 1 case when
```
if !completed {
    return false
}
```
will be called.
It's when you have expected and actual, but they are different.

2023-03-22 08:34 UTC, ice-nestor commented on levels-and-roles/completed_levels.go
> +				areLevelsCompleted(pr.CompletedLevels, Level1Type, Level2Type, Level3Type, Level4Type, Level5Type))) {
done

2023-03-22 08:34 UTC, ice-nestor commented on cmd/santa-sleigh/santa_sleigh.go
> +	// s.tasksProcessor = tasks.StartProcessor(ctx, cancel)
done

2023-03-23 05:02 UTC, ice-nestor commented on levels-and-roles/levels_and_roles_test.go
> +		},
added

2023-03-23 05:03 UTC, ice-nestor commented on levels-and-roles/completed_levels_test.go
> +	}
added, please re-check

2023-03-23 05:03 UTC, ice-nestor commented on levels-and-roles/completed_levels_test.go
> +			expected: map[string]struct{}{
added

2023-03-23 05:37 UTC, merged