Achieving tasks and levels with source processors
ice-blockchain/santa pull request #3
Opened 2022-05-18 14:36 UTC by nusanovkornilov-leftclick

[Task](https://www.notion.so/leftclick/Implement-Source-Processors-For-Achieving-Levels-Tasks-efea1ef41e7643eb8fa9fa5916af32d2)

2022-05-23 10:09 UTC, victor-oancea-leftclick-io requested changes
Too messy, no separation of concerns, bad file & folder structure

2022-05-23 10:09 UTC, victor-oancea-leftclick-io commented on achievements/badges.go
> +	badgeObject, err := r.GetBadge(ctx, badgeName)
Use sql instead for that

2022-05-23 10:09 UTC, victor-oancea-leftclick-io commented on achievements/messages/contract.go
> +package messages
Please don't create utils!

Put the logic where it belongs, in its domain

2022-05-23 10:09 UTC, victor-oancea-leftclick-io commented on achievements/badges.go
> +	// Send achieved badges to message broker because of we need to calculate total count of achieved badges (in achievementprocessor.badgeSourceProcessor).
Remove comment

2022-05-26 14:55 UTC, antonh21 requested changes
- A big question to such structure when we are creating a lot of processors at one package. It looks a bit messy and as a result, you have to use a crutch in the form of proxy processor. Dexter example was a bit another.
- From my side I need to recheck the logic better for levels/progress/tasks.
- For now some questions/problems here (let's discuss them as well).

2022-05-26 16:05 UTC, victor-oancea-leftclick-io requested changes

2022-05-26 16:05 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/badges/badges.go
> +func (r *repository) AchieveBadgesWithCompletedRequirements(ctx context.Context, userProgress *progress.UserProgress) error {
whats this for?

2022-05-26 16:06 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/badges/badges.go
> +	sql := `
that sql formatting is horror

2022-05-26 16:08 UTC, antonh21 commented on achievements/internal/storages/badges/badges.go
> +INSERT INTO ACHIEVED_USER_BADGES (USER_ID, BADGE_NAME, ACHIEVED_AT)
Seems this is double work for SQL.
Why not to do simple `SELECT` separately, then make `INSERT` based on this data and only after that send data to the topic.
```
SELECT [scan rows]
INSERT
```
Otherwise in your case:
```
INSERT SELECT [scan rows]
SELECT [again scan rows]
```

2022-05-26 16:10 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/badges/badges.go
> +INSERT INTO ACHIEVED_USER_BADGES (USER_ID, BADGE_NAME, ACHIEVED_AT)
the whole business logic is bizarre, I don't understand what he tries to do

2022-05-26 20:10 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +func (r *repository) AchieveBadge(ctx context.Context, userID UserID, badgeName BadgeName) error {
Yep, I moved this to another package (internal)

2022-05-26 20:13 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +		Key:     userID + badgeName,
It should be parsed (all data is presented in payload). Btw I'll update it with userID as Victor said

2022-05-26 20:19 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/levels/progress_source.go
> +		cfg.Levels.ConsecutiveMiningSessions = []uint32{90, 60, 30, 10, 5, 1}
Ok, I'll remove default values

2022-05-26 20:24 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/progress/agenda.go
> +func (r *repository) sendAgendaReferralsCountUpdate(ctx context.Context, userID UserID, countOfAgendaReferrals uint64) error {
Yep, we need to process updated count from agenda to increment level based on agenda referrals (10,5,1)

2022-05-26 20:49 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/contract.go
> +		publishAchievedBadgesTopic string
Found solution below, cfg directly, ok

2022-05-27 05:29 UTC, nusanovkornilov-leftclick commented on application.yaml
> +    port: 2443
to run in together with eskimo-hut on one machine

2022-05-27 05:47 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/progress/progress.go
> +	// Maybe it is better to pass global cfg from achievements here?
It seems I cant, cuz importing achievements package here will cause import cycle (achievements imports those internal packages to setup processors)

2022-05-27 06:44 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +    WHERE SOCIAL_BADGES.TYPE = 'SOCIAL'
yep, you're right, I didn't.
Tried with EXPLAIN QUERY PLAN now, it performs SCAN TABLE for social_badges, ice_badges and level_badges,  so I'll add a new index on badges table
`
3,0,0,SCAN TABLE BADGES AS SOCIAL_BADGES (~262144 rows)
4,0,0,SCAN TABLE BADGES AS ICE_BADGES (~262144 rows)
2,0,0,COMPOUND SUBQUERIES 3 AND 4 USING TEMP B-TREE (UNION)
5,0,0,SCAN TABLE BADGES AS LEVEL_BADGES (~262144 rows)
5,0,0,EXECUTE SCALAR SUBQUERY 6
6,0,0,SEARCH TABLE ACHIEVED_USER_LEVELS USING PRIMARY KEY (USER_ID=?) (~10 rows)
5,0,0,EXECUTE SCALAR SUBQUERY 7
7,0,0,SEARCH TABLE ACHIEVED_USER_LEVELS USING PRIMARY KEY (USER_ID=?) (~10 rows)
1,0,0,COMPOUND SUBQUERIES 2 AND 5 USING TEMP B-TREE (UNION)
0,0,0,SCAN SUBQUERY 1 AS BADGE_NAMES (~1 row)
0,1,1,SEARCH TABLE ACHIEVED_USER_BADGES USING PRIMARY KEY (USER_ID=? AND BADGE_NAME=?) (~1 row)
`

2022-05-30 12:44 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +		Key:     userID + badgeName,
removed badgeName here, so it is userID now

2022-05-30 12:45 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +UNION SELECT LEVEL_BADGES.NAME from  BADGES LEVEL_BADGES
That SQL is completely removed

2022-05-30 12:46 UTC, nusanovkornilov-leftclick commented on achievements/proxyprocessor.go
> +// SPDX-License-Identifier: BUSL-1.1
moved to achievements.go - is it the main.go file for achievements?

2022-05-30 12:46 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/badges/badges.go
> +func (r *repository) AchieveBadgesWithCompletedRequirements(ctx context.Context, userProgress *progress.UserProgress) error {
Removed

2022-05-30 12:48 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/tasks/users_source.go
> +func NewUserSource(db tarantool.Connector, mb messagebroker.Client) messagebroker.Processor {
Not sure if it is a good idea return repository from "NewUsersProcessor", for repository there is another public function for now

2022-05-30 12:49 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/tasks/users_source.go
> +		achievedTask := u.getCompletedTask(user)
there is multiple values for now, anyway I optimized error handling

2022-05-30 12:56 UTC, victor-oancea-leftclick-io commented on achievements/proxyprocessor.go
> +// SPDX-License-Identifier: BUSL-1.1
the entry point of every package is {packageName}.go -- except if you have multiple words, then its with `_` between words

2022-05-30 12:56 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/tasks/users_source.go
> +func NewUserSource(db tarantool.Connector, mb messagebroker.Client) messagebroker.Processor {
yep, separate func

2022-05-30 12:56 UTC, nusanovkornilov-leftclick commented on achievements/internal/storages/progress/contract.go
> +	//nolint:gomnd,nolintlint // 24 hour is session duration, and up to 10 hours between sessions
Without nolint it says it is the magic numbers in arithmetic operations:
`mnd: Magic number: 24, in <operation> detected (gomnd)`

2022-05-30 12:57 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/tasks/users_source.go
> +		achievedTask := u.getCompletedTask(user)
yea, that was an example before you transformed into array

2022-05-30 12:58 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/progress/contract.go
> +	//nolint:gomnd,nolintlint // 24 hour is session duration, and up to 10 hours between sessions
that one nolintlint

2022-05-30 13:30 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/tasks/users_source.go
> +// SPDX-License-Identifier: BUSL-1.1
drop them now

2022-05-30 13:31 UTC, victor-oancea-leftclick-io commented on achievements/internal/storages/tasks/users_source.go
> +// SPDX-License-Identifier: BUSL-1.1
don't avoid rebases and handling conflicts, embrace them, master them, thats how you get good at something and eventually start to enjoy it

2022-05-31 09:25 UTC, nusanovkornilov-leftclick commented on achievements/internal/badges/progress_source.go
> +		var criteriaValue math.Uint
I am using the same criteria for balance and T1referrals here, not sure if using ICEFlake to store referrals is a good idea :) So, it seems I need to separate logic

2022-05-31 09:40 UTC, victor-oancea-leftclick-io commented on achievements/internal/badges/progress_source.go
> +		var criteriaValue math.Uint
its a good time to try generics 😃 checkout the comparable interface

2022-05-31 09:52 UTC, victor-oancea-leftclick-io commented on achievements/internal/badges/progress_source.go
> +		var criteriaValue math.Uint
actually, you can't. Use a func that does the comparison for each type, don't make the intersection of types

2022-05-31 12:18 UTC, nusanovkornilov-leftclick commented on achievements/internal/badges/badges.go
> +	sql := `INSERT INTO achieved_user_badges(USER_ID, badge_name,   ACHIEVED_AT)
for the levels and tasks - the same, nosql? So idea is: source processors = nosql and RESTs = sql because of constraints?

2022-05-31 12:25 UTC, victor-oancea-leftclick-io commented on achievements/internal/badges/badges.go
> +	sql := `INSERT INTO achieved_user_badges(USER_ID, badge_name,   ACHIEVED_AT)
thats not a general rule, but yea, lets start with nosql for write operations in processors, and we'll see later on if we need some db checks in some of those write operations and we'll change them individually

2022-06-02 08:41 UTC, nusanovkornilov-leftclick commented on achievements/achievements.go
> +			switch len(result) {
what's ErrOrNil? I cant find anything like that in multierror and in ricky/dexter too

2022-06-02 09:11 UTC, victor-oancea-leftclick-io commented on achievements/achievements.go
> +			switch len(result) {
check for something similar in multierr

2023-01-05 15:11 UTC, merged