Postgres migration
ice-blockchain/santa pull request #6
Opened 2023-04-09 15:20 UTC by ice-myles

Database migration from tarantool to postgres.

2023-05-30 11:09 UTC, ice-ares commented on badges/DDL.sql
> +                        balance          TEXT
lets make this float64, and move it at the top

2023-05-30 11:35 UTC, ice-cronus commented on badges/DDL.sql
> +                        balance          TEXT
Will we modify wintr as well? For now [Scan() supports only string](https://github.com/ice-blockchain/wintr/blob/master/coin/coin.go#L266)

2023-05-30 11:54 UTC, ice-ares commented on badges/DDL.sql
> +                        balance          TEXT
https://github.com/ice-blockchain/freezer/blob/6bf7b963d4e33f81404d626266cdf5e54c7d3996/balance-synchronizer/contract.go#L16

2023-05-31 16:43 UTC, ice-ares commented on badges/DDL.sql
> +                        balance          DOUBLE PRECISION,
NUMERIC(20,20) NOT NULL DEFAULT 0,

run this to see if you placed the column at the right place:

```
SELECT a.attname, t.typname, t.typalign, t.typlen
FROM pg_class c
JOIN pg_attribute a ON (a.attrelid = c.oid)
JOIN pg_type t ON (t.oid = a.atttypid)
WHERE c.relname = 'badge_progress'
 AND a.attnum >= 0
ORDER BY t.typlen DESC;
```

2023-05-31 16:44 UTC, ice-ares commented on badges/DDL.sql
> +                    );
) WITH (fillfactor = 70);

2023-05-31 16:44 UTC, ice-ares commented on badges/DDL.sql
> +                 );
) WITH (fillfactor = 70);

2023-05-31 16:45 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                    );
) WITH (fillfactor = 70);

2023-05-31 16:49 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        phone_number_hash           TEXT
do we still need this?

2023-05-31 16:56 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        last_ping_cooldown_ended_at  TIMESTAMP NOT NULL,
not a good idea, add a regular int instead, add a new field in the husky msg struct for it which has the value:

```
func PingNumber(date *time.Time, cooldownDeadline stdlibtime.Duration) uint64 {
	return uint32(uint64(date.Unix()) / uint64(cooldownDeadline/stdlibtime.Second))
}
```

Cuz otherwise if the message gets sent a 2nd time, you increase the ping counter again

2023-05-31 16:57 UTC, ice-ares commented on tasks/DDL.sql
> +                    );
) WITH (fillfactor = 70);

2023-05-31 17:52 UTC, ice-ares commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
this whole referrals * referrals count looks messy.

Lets try this:

1. add a date to this column and make this with a 24h ttl expiration ( just like husky/analytics/actions)
2. drop the  `CREATE INDEX IF NOT EXISTS referrals_referred_by_ix ON referrals (referred_by);`
3. move all the friends/referrals invited logic to a separate package named `friends-invited`
3.1. In this new package listen ONLY on empty to nonempty referredBy changes from the users table source (because non empty to nonempty would mean t0 deleted the account and the user was assigned a different t0, which is not his "friend", cuz he doesnt know anything about him)
3.2. then doInTransaction ( insert into this table, if conflict => return, else friends_invited.amount++ returning * where friends_invited.user_id = referredBy, if ok , send message to broker with userId:friendsInvited)
3.2.1 friends_invited is a new table (bigint not null default 0, user_id text not null primary key)
4. on all the other packages consume from that topic and just replace the amount in their specific tables

2023-05-31 17:59 UTC, ice-ares commented on application.yaml
> +      - name: referral-counts
name this `friends-invited`

2023-05-31 18:01 UTC, ice-ares commented on badges/achieve_badges.go
> +									SET achieved_badges = $1
use excluded.

2023-05-31 18:04 UTC, ice-ares commented on badges/achieve_badges.go
> +				achieved = *p.Balance > float64(repo.cfg.Milestones[badgeType].FromInclusive)
gte

2023-05-31 18:05 UTC, ice-ares commented on badges/achieve_badges.go
> +				achieved = *p.Balance > float64(repo.cfg.Milestones[badgeType].FromInclusive)
also, make the config fields be float64 instead of casting everywhere

2023-05-31 18:08 UTC, ice-ares commented on badges/achieve_badges.go
> +func (s *userTableSource) insertReferrals(ctx context.Context, us *users.UserSnapshot) error {
this whole method is gonna change a lot, im leaving this comment here to help me remember I need to recheck it

2023-05-31 18:09 UTC, ice-ares commented on badges/achieve_badges_test.go
> +		Balance:         &balance,
doesnt have to be nil

2023-05-31 18:10 UTC, ice-ares commented on badges/badges.go
> +		&referralCountsSource{processor: prc},
invitedFriendsSource

2023-05-31 18:10 UTC, ice-ares commented on badges/badges.go
> +		&referralCountsSource{processor: prc},
or friendsInvitedSource, pick the one that is consisted with everything else

2023-05-31 18:11 UTC, ice-ares commented on badges/contract.go
> +		Balance         *float64          `json:"balance,omitempty" example:"1232323232.56"`
not nil pls

2023-05-31 18:12 UTC, ice-ares commented on badges/get_badges.go
> +	offset := 0
whats this for?

2023-05-31 18:13 UTC, ice-ares commented on go.mod
> +	github.com/ice-blockchain/go-tarantool-client v0.0.0-20230327200757-4fc71fa3f7bb
why is this still here?

2023-05-31 18:18 UTC, ice-ares commented on levels-and-roles/completed_levels_and_activated_roles.go
> +	sql := `INSERT INTO pings(user_id, pinged_by,last_ping_cooldown_ended_at) VALUES ($1,$2, $3)`
we need a periodic cleanup on this

2023-05-31 18:19 UTC, ice-ares commented on levels-and-roles/completed_levels_and_activated_roles.go
> +				SET phone_number_hash = $2,
use excluded

2023-05-31 18:20 UTC, ice-ares commented on levels-and-roles/completed_levels_and_activated_roles.go
> -		errors.Wrapf(s.updateAgendaContactsJoined(ctx, us), "failed to updateAgendaContactsJoined for user:%#v", us),
whats the new approach for this one?

2023-05-31 18:21 UTC, ice-ares commented on levels-and-roles/completed_levels_and_activated_roles.go
> +func (s *userTableSource) insertNewReferrals(ctx context.Context, us *users.UserSnapshot) error {
this whole method is gonna change a lot, im leaving this comment here to help me remember I need to recheck it

2023-05-31 18:31 UTC, ice-ares commented on levels-and-roles/contacts_source.go
> +	sql := fmt.Sprintf(`INSERT INTO levels_and_roles_progress(user_id, contact_user_ids, agenda_contacts_joined) VALUES ($1, $2, $3)
why do you need 2 sources for the same information? agenda_contacts_joined == Len(contact_user_ids)

2023-05-31 18:32 UTC, ice-ares commented on levels-and-roles/contacts_source.go
> +					   OR levels_and_roles_progress.agenda_contacts_joined != EXCLUDED.agenda_contacts_joined`, sign)
this is pointless cuz EXCLUDED.agenda_contacts_joined is always 1

2023-05-31 18:33 UTC, ice-ares commented on levels-and-roles/contract.go
> +		ContactUserIDs       *users.Enum[string]    `json:"contactUserIDs,omitempty" example:"edfd8c02-75e0-4687-9ac2-1ce4723865c4,edfd8c02-75e0-4687-9ac2-1ce4723865c5" db:"contact_user_ids"` //nolint:lll
Lets pls try to rename everything to AgendaContactXXX

2023-05-31 18:34 UTC, ice-ares commented on tasks/complete_tasks.go
> +	var updatedRows uint64
drop this and use a different name for err

2023-05-31 18:39 UTC, ice-ares commented on tasks/complete_tasks.go
>  		if err = r.awardAllTasksCompletionICECoinsBonus(ctx, userID); err != nil {
drop this flow entirely, we're using now a pull approach in freezer, instead of this push one

2023-05-31 18:40 UTC, ice-ares commented on tasks/complete_tasks.go
>  		if err = r.awardAllTasksCompletionICECoinsBonus(ctx, userID); err != nil {
meaning prizes are awarded in freezer by subscribing to the completed tasks topic

2023-05-31 18:41 UTC, ice-ares commented on tasks/complete_tasks.go
> +			ON CONFLICT(user_id) DO UPDATE SET mining_started = true;`
add where clause to all these on conflict sql, to minimize insert load

2023-05-31 18:42 UTC, ice-ares commented on tasks/complete_tasks.go
> +func (s *userTableSource) insertReferrals(ctx context.Context, us *users.UserSnapshot) error {
TODO: check this again

2023-05-31 18:43 UTC, ice-ares commented on tasks/complete_tasks.go
> +func (r *repository) sendReferralsCountUpdate(ctx context.Context, userID string) error {
this has to be done once, in that new package, not in all 3 like it is atm

2023-05-31 18:44 UTC, ice-ares commented on tasks/complete_tasks.go
> +	_, errDelRefs := storage.Exec(ctx, s.db, `DELETE FROM referrals WHERE user_id = $1 OR referred_by = $1`, params...)
TODO check this again

2023-05-31 19:57 UTC, ice-ares commented on badges/DDL.sql
> +                        balance          DOUBLE PRECISION,
actually no, its not worth it. Let's use bigint and cast float64 to int64 before u insert it. Configurations are all natural numbers anyway

2023-06-01 08:11 UTC, ice-cronus commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
why doInTransaction? It would be triggered on each user creation (cuz referred by is required), but u said before to avoid that in eskimo's user creation flow

2023-06-01 08:27 UTC, ice-ares commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
cuz this one is async, and that one is sync, and there’s not alot of req/s for user registration

2023-06-01 08:29 UTC, ice-ares commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
And ofc, we care a bit more here about atomicity than performance, atleast 51:49

2023-06-01 12:41 UTC, ice-cronus commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
> 2. drop the CREATE INDEX IF NOT EXISTS referrals_referred_by_ix ON referrals (referred_by);


We probably need that index for deletion of referrals on users deletion, there is `DELETE FROM referrals WHERE user_id = $1 or referred_by = $1`. Or we dont worry about it anymore because of periodical deletion task?

2023-06-01 13:08 UTC, ice-cronus commented on levels-and-roles/DDL.sql
> +                        phone_number_hash           TEXT
As I remember there are business requirements like we count agenda contacts if user provided phone number, and it is still implemented in level achieving logic. But eskimo it seems does not check if agenda owner provided his own number when sending contacts, so yes, we still need this.

2023-06-01 13:23 UTC, ice-ares commented on tasks/DDL.sql
> +CREATE TABLE IF NOT EXISTS referrals (
Yea, it doesn’t matter cuz of 1.

2023-06-01 13:23 UTC, ice-cronus commented on levels-and-roles/DDL.sql
> +                        last_ping_cooldown_ended_at  TIMESTAMP NOT NULL,
Hmm, in husky we're detecting ping duplicates based on [the same field LastPingCooldownEndedAt](https://github.com/ice-blockchain/husky/blob/master/notifications/users.go#L365), so I thought it is unique for ping message. Do we need to add extra column in husky as well? Or it is worse cuz it is calculated?

2023-06-01 13:24 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        phone_number_hash           TEXT
I dont think we do, right @ice-myles ?

2023-06-01 13:25 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        last_ping_cooldown_ended_at  TIMESTAMP NOT NULL,
Neah, u’re right

2023-06-02 07:31 UTC, ice-cronus commented on levels-and-roles/completed_levels_and_activated_roles.go
> -		errors.Wrapf(s.updateAgendaContactsJoined(ctx, us), "failed to updateAgendaContactsJoined for user:%#v", us),
agendaContactsSource is being used instead

2023-06-06 06:27 UTC, ice-ares requested changes

2023-06-06 06:27 UTC, ice-ares commented on badges/contract.go
> +		Balance         uint64            `json:"balance,omitempty" example:"1232323232"`
keep the existing contract with the app, which is string

2023-06-06 06:27 UTC, ice-ares commented on cmd/santa-sleigh/santa_sleigh.go
> +	s.friendsProcessor = friendsinvited.StartProcessor(ctx, cancel)
friendsInvited

2023-06-06 06:27 UTC, ice-ares commented on friends-invited/DDL.sql
> +                                         PRIMARY KEY(user_id, referred_by, processed_at)
Only user id

2023-06-06 06:27 UTC, ice-ares commented on friends-invited/contract.go
> +		Count  uint64 `json:"count" example:"5"`
FriendsInvited

2023-06-06 06:27 UTC, ice-ares commented on friends-invited/contract.go
> +	friendsInvited struct {
Use the public struct

2023-06-06 06:27 UTC, ice-ares commented on friends-invited/users.go
> +	_, errDelUser := storage.Exec(ctx, s.db, `DELETE FROM friends_invited WHERE user_id = $1`, us.Before.ID)
U need to also decrement counter for t0 when a t1 deletes their account

2023-06-06 06:27 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        phone_number_hash           TEXT
@ice-myles do we need that column?

2023-06-06 06:27 UTC, ice-ares commented on levels-and-roles/contacts_source.go
> +	sql := `INSERT INTO levels_and_roles_progress(user_id, agenda_contact_user_ids, agenda_contacts_joined) VALUES ($1, $2, array_length($2::TEXT[],1))
Why do u need this? Just check len(contacts) when needed

2023-06-06 06:27 UTC, ice-ares commented on levels-and-roles/DDL.sql
> +                        agenda_contacts_joined      BIGINT NOT NULL DEFAULT 0,
U dont need thjs

2023-06-06 06:27 UTC, ice-ares commented on levels-and-roles/contract.go
> +		PhoneNumberHash      *string                `json:"phoneNumberHash,omitempty" example:"some hash"`
Is this needed?

2023-06-06 06:27 UTC, ice-ares commented on tasks/complete_tasks.go
> +									WHERE COALESCE(task_progress.pseudo_completed_tasks,ARRAY[]::TEXT[]) = COALESCE($2,ARRAY[]::TEXT[])`,
Excluded, everywhere!

2023-06-06 06:49 UTC, ice-cronus commented on levels-and-roles/contacts_source.go
> +	sql := `INSERT INTO levels_and_roles_progress(user_id, agenda_contact_user_ids, agenda_contacts_joined) VALUES ($1, $2, array_length($2::TEXT[],1))
We would lose that select * then, because it would be calculated field

2023-06-06 07:12 UTC, ice-cronus commented on tasks/complete_tasks.go
> +									WHERE COALESCE(task_progress.pseudo_completed_tasks,ARRAY[]::TEXT[]) = COALESCE($2,ARRAY[]::TEXT[])`,
We cant use excluded here, cuz it is not reducing wrting load here, but detecting race condition. Excluded = $3, $2 is the previous state to update only once

2023-06-06 07:32 UTC, ice-cronus commented on levels-and-roles/contacts_source.go
> +	sql := `INSERT INTO levels_and_roles_progress(user_id, agenda_contact_user_ids, agenda_contacts_joined) VALUES ($1, $2, array_length($2::TEXT[],1))
ah, I see, u mean golang len()

2023-06-06 07:43 UTC, ice-myles commented on levels-and-roles/DDL.sql
> +                        phone_number_hash           TEXT
Yes, we need this column due to this check
https://github.com/ice-blockchain/santa/blob/feature/postgres-migration/levels-and-roles/completed_levels_and_activated_roles.go#L392

We check the phone number hash to complete level related to `AgendaContactsJoinedMilestones`.

2023-06-06 07:47 UTC, ice-myles commented on badges/contract.go
> +		Balance         uint64            `json:"balance,omitempty" example:"1232323232"`
Why? We specially changed this field to uint64 due to we get float from freezer.

2023-06-06 07:50 UTC, ice-cronus commented on badges/contract.go
> +		Balance         uint64            `json:"balance,omitempty" example:"1232323232"`
Probably because of overflows, there are 2^256 iceflakes, 2^256 / 1e9 = 1.15e68 ice, log(2,1e68) = 225 bits

2023-06-06 07:55 UTC, ice-ares commented on badges/contract.go
> +		Balance         uint64            `json:"balance,omitempty" example:"1232323232"`
No, i meant for the app, if this is used to return something to the app, it has to be string, if its something we use internally it has to be float64

2023-06-06 08:13 UTC, ice-myles commented on badges/contract.go
> +		Balance         uint64            `json:"balance,omitempty" example:"1232323232"`
We use this internally. `GetBadges` and `GetSummary` endpoints don't use and don't return balance to the app. And we decided before to use uint64 for balance because milestones from the configuration file are uint64 (integers).

2023-06-06 09:26 UTC, merged