Tasks API
ice-blockchain/santa pull request #8
Opened 2023-01-16 09:34 UTC by ice-nestor

Add an API for completing and getting tasks

[reference](https://www.notion.so/Tasks-API-e2c7a64658314541876ea2a9fadaebd0)

2023-01-16 09:46 UTC, ice-ares commented on cmd/santa-sleigh/contract.go
> +	Task struct {
remove this

2023-01-16 09:48 UTC, ice-ares commented on cmd/santa-sleigh/contract.go
> +	CompleteTaskArg struct {
check eskimo to see everything you need for a request body

2023-01-16 17:31 UTC, bejaneps commented on cmd/santa-sleigh/contract.go
> +	Task struct {
we have same design in eskimo, should I reference tasks.Task structure in request and response directly instead ?

2023-01-16 17:33 UTC, bejaneps commented on cmd/santa-sleigh/contract.go
> +	CompleteTaskArg struct {
eskimo has different fields for different requests, which one you mean ?

2023-01-16 18:01 UTC, ice-nestor commented on cmd/santa-sleigh/contract.go
> +	Task struct {
we have same design in eskimo, do you want me to use tasks.Task directly ?

2023-01-18 11:01 UTC, ice-cronus requested changes

2023-01-18 11:01 UTC, ice-cronus commented on tasks/users_source.go
> +		return nil
delete user_progress? It seems to be nesesary as we have CASCADE in DDL

2023-01-18 11:32 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if completedTask.TaskName == taskSocialShare {
https://github.com/ice-blockchain/santa/pull/8/files#diff-d4f56637ea2a8978b4e349ff775ef86929c8da5cbd2cdf98d710afc0bb0f566fR48 

what about with this functionality ?

2023-01-18 12:38 UTC, ice-nestor commented on tasks/users_source.go
> +		return nil
Thanks, added

2023-01-18 12:59 UTC, ice-myles requested changes

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +		return 0, nil
Why do you return no error if record is not found? This is error as well, that should be handled and the further execution should be stopped or at least this problem should be logged.

2023-01-18 12:59 UTC, ice-myles commented on tasks/progress.go
> +	if len(res) == 0 {
Why do you return nil here and not `storage.ErrNotFound`?
You tried to insert data into the database, you didn't give an error, but you didn't give the result. Seems like it's wrong behaviour.

2023-01-18 12:59 UTC, ice-myles commented on tasks/progress.go
> +		return 0, nil
The same, maybe `storage.ErrNotFound` needed here instead of nil returning?

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +	if user.ReferredBy == "" {
This is not needed as user always have the referreedBy initially.

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +Eskimo doesn't fill user.ProfilePictureURL properly, it's better to add/use another field
If you mean that you have filename only without full path, so you can use picture client to get download path as it done at eskimo:
``
pictureClient.DownloadURL(profilePictureURL)
``

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +	defaultUserPictureName := u.cfg.Tasks.DefaultUserPictureName
As I remember user gets one from 20 numbers of random pictures names. You can look into `RandomDefaultProfilePictureName` const at the eskimo.
Did you handle all of them or only 1?

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +	return user.Username != "" && (user.Before == nil || user.Before.Username == "")
`user.Before == nil` is the case when user is created (Before is nil, User is not empty). On user creation we give random username to the user.
So it means that if you are going to handle this case, the user will get such achievement on registration when he even did't do anything. Is it right scenario?

2023-01-18 12:59 UTC, ice-myles commented on tasks/users_source.go
> +	t1Referrals, err = u.repository.updateT1ReferralsCount(user.ReferredBy, 1)
And what if there was user removing or modifying, and as result somebody was removed, and it means referredBy was changed for somebody else? In simple words: plus 1 here must be all the time here?

2023-01-18 12:59 UTC, ice-myles commented on tasks/tasks_complete.go
> +	if err = storage.CheckSQLDMLErr(query, err); err != nil {
```
-query, err := r.db.PrepareExecute(sql, params)
-if err = storage.CheckSQLDMLErr(query, err); err != nil {
+if err = storage.CheckSQLDMLErr(r.db.PrepareExecute(sql, params)); err != nil {
```
And you will save 1 line.

2023-01-18 13:17 UTC, ice-nestor commented on tasks/progress.go
> +	if len(res) == 0 {
if db didn't return record on insert why `storage.ErrNotFound`, maybe to return something else ?

2023-01-18 13:21 UTC, ice-nestor commented on tasks/users_source.go
> +	return user.Username != "" && (user.Before == nil || user.Before.Username == "")
User should complete the task on registration right, when he gets his first nickname

2023-01-18 13:23 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	return res, nil
1st task is always done by default when user is registered

2023-01-18 13:25 UTC, ice-myles commented on tasks/progress.go
> +	if len(res) == 0 {
From go-tarantool code:
```
// InsertTyped performs insertion to box space.
// Tarantool will reject Insert when tuple with same primary key exists.
//
// It is equal to conn.InsertAsync(space, tuple).GetTyped(&result).
```
Check `getEmailValidation` as example in the eskimo to see example of `GetTyped` usage:
```
result := new(EmailValidation)
	err := r.db.GetTyped("EMAIL_VALIDATIONS", "pk_unnamed_EMAIL_VALIDATIONS_1", tarantool.StringKey{S: id}, result)
	if err == nil && result.UserID == "" {
		err = storage.ErrNotFound
	}
```
Maybe I am not right, but it worths to check. Seems like if you tried to insert a record, and you `res` variable is empty, it means that you didn't insert this record. No?

2023-01-18 13:45 UTC, ice-myles commented on tasks/users_source.go
> +	defaultUserPictureName := u.cfg.Tasks.DefaultUserPictureName
And if that needed at all to handle random pictures?

2023-01-18 13:46 UTC, ice-myles commented on tasks/users_source.go
> +	return user.Username != "" && (user.Before == nil || user.Before.Username == "")
Yes, but when user types his new nickname on registration, modifyUser request is sent to the eskimo.

2023-01-18 14:53 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		msg, err = r.prepareRewardMessage(completedTask.UserID)
Changed

2023-01-18 14:54 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if err = storage.CheckSQLDMLErr(query, err); err != nil {
Changed

2023-01-18 14:54 UTC, ice-nestor commented on tasks/progress.go
> +	sql := fmt.Sprintf(`DELETE FROM %v WHERE user_id = :userID`, userProgressSpace)
Changed

2023-01-18 14:54 UTC, ice-nestor commented on tasks/users_source.go
> +	t1Referrals, err = u.repository.updateT1ReferralsCount(ctx, user.ReferredBy, 1)
Added new functionality

2023-01-18 14:54 UTC, ice-nestor commented on go.mod
>  go 1.18
Updated

2023-01-18 14:54 UTC, ice-nestor commented on tasks/progress.go
> +package tasks
Added

2023-01-18 14:54 UTC, ice-nestor commented on tasks/progress.go
> +		return nil, errors.Wrapf(err, "unable to get user_achievements record for userID:%v", userID)
Changed

2023-01-18 14:54 UTC, ice-nestor commented on tasks/progress.go
> +		return nil, errors.Wrapf(storage.ErrNotFound, "no user achievements record for userID:%v", userID)
Changed

2023-01-18 14:54 UTC, ice-nestor commented on tasks/progress.go
> +	ua := &UserProgress{
Changed

2023-01-18 14:55 UTC, ice-nestor commented on tasks/progress.go
> +	if len(res) == 0 {
Changed

2023-01-18 14:55 UTC, ice-nestor commented on tasks/progress.go
> +		return 0, nil
Changed

2023-01-18 14:55 UTC, ice-nestor commented on tasks/users_source.go
> +	if user.ReferredBy == "" {
Changed

2023-01-18 14:56 UTC, ice-nestor commented on tasks/users_source.go
> +	t1Referrals, err = u.repository.updateT1ReferralsCount(user.ReferredBy, 1)
Changed

2023-01-18 15:25 UTC, ice-myles commented on tasks/users_source.go
> +	if user.User == nil {
Better to check `Before` as well to be sure in the logic.
```
if snapshot.User == nil && snapshot.Before != nil {
```
And please rename arg in the function:
```
-handleUserProgress(user *users.UserSnapshot)
+handleUserProgress(snapshot *users.UserSnapshot)
```
As we check not an user, but snapshot.

2023-01-18 15:57 UTC, ice-cronus requested changes

2023-01-18 15:57 UTC, ice-cronus commented on tasks/tasks_complete.go
> +	if err := r.verifyPreviousTasks(task); err != nil {
are u sure if it is a good idea to verify on complection for previous tasks on completion of the next one? I.e case: user registered, uploaded a profile picture first (no task achieved cuz he did not start mining yet, user at task1) and then started mining (achieved task2), and to complete task 3 you should wait for next user update event in message broker, when you will be able to get information about profile picture. In my opinion with above example user should get both 2 and 3 tasks when he starts mining if he uploaded a picture before (may be it is better to move this verification to getTasks endpoint)

2023-01-18 15:57 UTC, ice-cronus commented on tasks/tasks_get.go
> +	for _, task := range res {
I think you can do it in one loop if both lists are sorted in the same order (by index?)

2023-01-18 15:57 UTC, ice-cronus commented on tasks/users_source.go
> +	t1Referrals, err = u.repository.updateT1ReferralsCount(user.ReferredBy, -1)
here should be user.Before.ReferredBy, isn't it? user.ReferredBy is empty because user is deleted

2023-01-19 10:58 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if err := r.verifyPreviousTasks(task); err != nil {
imo makes sense

2023-01-19 11:01 UTC, ice-nestor commented on tasks/tasks_get.go
> +	for _, task := range res {
`AchievedTask` doesn't have index in structure definition, but I could add it for the sake of this loop ?

2023-01-19 11:50 UTC, ice-ares commented on tasks/tasks_complete.go
> +	if err := r.verifyPreviousTasks(task); err != nil {
You keep the state required to check if each task is completed or not.

every time you verify for a task completion, you check if the previous tasks are also completed to mark that task as completed.


IE 
I have 5 referrals. Task is not completed in DB.

I set my profile picture, referrals task is still not completed. 

I start mining, referrals task is still not completed. 

I join telegram, referrals task is still not completed. 

i follow twitter, boom, check if user still has 5 referrals, mark it completed

2023-01-20 14:07 UTC, ice-nestor commented on tasks/users_source.go
> +	t1Referrals, err = u.repository.updateT1ReferralsCount(user.ReferredBy, -1)
done

2023-01-20 14:07 UTC, ice-nestor commented on tasks/users_source.go
> +	if user.User == nil {
done

2023-01-20 14:55 UTC, ice-nestor commented on tasks/users_source.go
> +		return 0, nil
done

2023-01-20 14:56 UTC, ice-nestor commented on tasks/users_source.go
> +	return user.Username != "" && (user.Before == nil || user.Before.Username == "")
done

2023-01-23 03:33 UTC, ice-myles requested changes

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +		return u.handleUserDeleted(snapshot)
Wrap please this error.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +		return u.handleUserCreated(snapshot)
Wrap please this error.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +		return u.handleReferredByChanged(snapshot)
Wrap please this error.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +	return t1Referrals, u.deleteUserProgress(snapshot.ID)
Wrap please `u.deleteUserProgress(snapshot.ID)` error.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before == nil || snapshot.Before.Username == "")
`snapshot.Before == nil || snapshot.Before.Username == ""` will check user creation, not user modification, but seems like you need to check user modification here.
Claiming nickname is when you created user (called CreateUser endpoint) and then you suggest to change nickname for him. When he types nickname and send new nickname, ModifyUser endpoint is called.

User modification is:
```
return snapshot.Username != "" && (snapshot.Before != nil)
```

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +		"userID":     task.UserID,
```
-"userID": task.UserID,
+"userId": task.UserID,
```

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +	sql := fmt.Sprintf("INSERT INTO %v (USER_ID, TASK_NAME, ACHIEVED_AT) VALUES (:userID, :taskName, :achievedAt)", achievedTasksSpace)
```
-VALUES (:userID,
+VALUES (:userId,
```

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +	return t1Referrals, u.repository.insertUserProgress(snapshot.User)
Wrap please ```u.repository.insertUserProgress(snapshot.User)``` error.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +	return t1Referrals, err
```
-return t1Referrals, err
+return t1Referrals, nil
```
The same, but will be clearer.

2023-01-23 03:33 UTC, ice-myles commented on tasks/users_source.go
> +		result = multierror.Append(result, errors.Wrapf(err, "failed to handle user creation event for userID:%v", user.ID))
Not needed multierror for this error handling as I see. It's separate error case. For completed tasks - yes, but here - no.

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +func (r *repository) send(ctx context.Context, msgBody any, msgKey, topic string) error {
Let's rename this function to smth better. What are you sending here?

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +func (r *repository) checkIfTasksAreInList(tasksIndex int, previousTasks []*AchievedTask) bool {
`tasksIndex` is not simple tasks index, this is some kind of upper bound. So it would be nice to rename this arg to smth decent to make this function more clear.

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +	return r.sendCompleteTask(ctx, now, task)
Wrap this function to errors.Wrap/Wrapf please.

2023-01-23 03:33 UTC, ice-myles commented on tasks/tasks_complete.go
> +		sql += ", (:userID, 'PRIZE', :achievedAt)"
```
-(:userID, 'PRIZE',
+(:userId, 'PRIZE',
```

2023-01-23 05:28 UTC, ice-cronus requested changes

2023-01-23 05:28 UTC, ice-cronus commented on tasks/contract.go
> +		MessageBroker struct {
it is better to use `messagebroker.Config `mapstructure:",squash"`` from wintr

2023-01-23 05:28 UTC, ice-cronus commented on tasks/contract.go
> +			DefaultUserPictureName string `yaml:"defaultUserPictureName"`
you , probably, should change it to regexp as eskimo has 20 random pictures for now. Or to remove it from config completely, create a const instead

2023-01-23 11:50 UTC, ice-nestor commented on tasks/contract.go
> +		MessageBroker struct {
done

2023-01-23 11:50 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		sql += ", (:userID, 'PRIZE', :achievedAt)"
done

2023-01-23 11:50 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	return r.sendCompleteTask(ctx, now, task)
done

2023-01-23 11:50 UTC, ice-nestor commented on tasks/tasks_complete.go
> +func (r *repository) checkIfTasksAreInList(tasksIndex int, previousTasks []*AchievedTask) bool {
removed

2023-01-23 11:50 UTC, ice-nestor commented on tasks/tasks_complete.go
> +func (r *repository) send(ctx context.Context, msgBody any, msgKey, topic string) error {
done

2023-01-23 11:50 UTC, ice-nestor commented on tasks/users_source.go
> +		result = multierror.Append(result, errors.Wrapf(err, "failed to handle user creation event for userID:%v", user.ID))
done

2023-01-23 11:50 UTC, ice-nestor commented on tasks/users_source.go
> +	return t1Referrals, err
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +	return t1Referrals, u.repository.insertUserProgress(snapshot.User)
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	sql := fmt.Sprintf("INSERT INTO %v (USER_ID, TASK_NAME, ACHIEVED_AT) VALUES (:userID, :taskName, :achievedAt)", achievedTasksSpace)
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		"userID":     task.UserID,
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before == nil || snapshot.Before.Username == "")
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +	return t1Referrals, u.deleteUserProgress(snapshot.ID)
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +		return u.handleReferredByChanged(snapshot)
will move this to separate package as discussed

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +		return u.handleUserCreated(snapshot)
will move this to separate package as discussed

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +		return u.handleUserDeleted(snapshot)
will move this to separate package as discussed

2023-01-23 11:51 UTC, ice-nestor commented on tasks/users_source.go
> +	_, err = u.repository.getUserProgress(snapshot.ID)
will move this to separate package as discussed

2023-01-23 11:51 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		{body: reward, topic: r.cfg.MessageBroker.Topics[8].Name},
done

2023-01-23 11:51 UTC, ice-nestor commented on tasks/progress.go
> +		"userID": userID,
done

2023-01-23 11:52 UTC, ice-nestor commented on tasks/progress.go
> +func (r *repository) updateT1ReferralsCount(userID string, diff int64) (t1Refferals uint64, err error) {
done

2023-01-23 11:52 UTC, ice-nestor commented on tasks/progress.go
> +func (r *repository) getUserProgress(userID string) (*UserProgress, error) {
done

2023-01-24 09:22 UTC, ice-myles commented on tasks/users_source.go
> +	return user.Username != "" && (user.Before == nil || user.Before.Username == "")
Not done

2023-01-24 09:26 UTC, ice-myles commented on tasks/tasks_complete.go
> +	if err := r.db.SelectTyped(achievedTasksSpace, "pk_unnamed_ACHIEVED_USER_TASKS_1", 0, limit, tarantool.IterEq, partialKey, &res); err != nil {
So why do you allocate only 1 item for res if you want to get more?

2023-01-24 09:28 UTC, ice-nestor commented on tasks/contract.go
> +			DefaultUserPictureName string `yaml:"defaultUserPictureName"`
added

2023-01-24 09:28 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if err := r.db.SelectTyped(achievedTasksSpace, "pk_unnamed_ACHIEVED_USER_TASKS_1", 0, limit, tarantool.IterEq, partialKey, &res); err != nil {
because, I'm not sure how many items I will get

2023-01-24 09:32 UTC, ice-nestor commented on tasks/users_source.go
> +	defaultUserPictureName := u.cfg.Tasks.DefaultUserPictureName
Added this for below discussion

2023-01-24 09:33 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if err := r.db.SelectTyped(achievedTasksSpace, "pk_unnamed_ACHIEVED_USER_TASKS_1", 0, limit, tarantool.IterEq, partialKey, &res); err != nil {
it could be 0, 1 or more

2023-01-24 10:12 UTC, ice-nestor commented on tasks/tasks_get.go
> +	for _, task := range res {
and it's just 1-8 records in each list, I don't think 1 loop or 2 loops would make big difference

2023-01-24 10:13 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if err := r.verifyPreviousTasks(task); err != nil {
added

2023-01-24 10:13 UTC, ice-nestor commented on tasks/users_source.go
> +Eskimo doesn't fill user.ProfilePictureURL properly, it's better to add/use another field
Added this for below discussion

2023-01-24 10:16 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if completedTask.TaskName == taskSocialShare {
added fix

2023-01-24 10:49 UTC, ice-myles requested changes

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	if err := r.db.SelectTyped(achievedTasksSpace, "pk_unnamed_ACHIEVED_USER_TASKS_1", 0, limit, tarantool.IterEq, partialKey, &res); err != nil {
Then
```
Map: An empty map is allocated with enough space to hold the
specified number of elements. The size may be omitted, in which case
a small starting size is allocated.

res := make([]*AchievedTask, 0)
```

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	// Append sequentially each next task that is achieved, if next sequential isn't found then stop
Please remove these comments as the description is seen from the code.

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +			return err
Wrap this error please.

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +		// Send reward message to freezer.
Please remove the comments as 
`// Send reward message to freezer.`
The logic is seen well from the code and topic's name in the comment.

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	return errors.Wrapf(r.sendCompleteTask(ctx, now, task), "failed to send completed task for task %v and userID:%v", task.Name, task.UserID)
If complete task message wasn't sent, I assume we need to revert completing task from the database as consumers will not know about this, is it right @ice-ares?

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	nextAchievedTasks := make([]*AchievedTask, 0, 1)
`make([]*AchievedTask, 0)` here.

```
Map: An empty map is allocated with enough space to hold the
specified number of elements. The size may be omitted, in which case
a small starting size is allocated.
```

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	return errors.Wrapf(r.sendMsg(ctx, completedTask, completedTask.UserID, r.cfg.MessageBroker.Topics[0].Name),
Add please topic name in the comment
```
return errors.Wrapf(r.sendMsg(ctx, completedTask, completedTask.UserID, r.cfg.MessageBroker.Topics[0].Name), // | some-topic-name
```

2023-01-24 10:49 UTC, ice-myles commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before != nil)
```
return snapshot.Username != "" && snapshot.Before != nil && snapshot.User != nil
```

2023-01-24 10:49 UTC, ice-myles commented on tasks/users_source.go
> +	return (!u.defaultProfilePictureNameRegex.MatchString(snapshot.ProfilePictureURL)) && (snapshot.Before == nil || hadDefaultPictureBefore)
I assume the main points you need to check here are:
- if it was modify request
- if the current picture not default and not empty
- if the current picture is not equal to the picture  before

Because at the CreateUser endpoint user has already had the default picture, always, so no sense to check this case.
Then he can either modify to his own, or reset to default picture when he already has some own picture. 

```
func (u *usersSource) isProfilePictureUploaded(snapshot *users.UserSnapshot) bool {
	if snapshot.User == nil || snapshot.Before == nil {
		return false
	}
	if snapshot.ProfilePictureURL == "" || u.defaultProfilePictureNameRegex.MatchString(snapshot.ProfilePictureURL) {
		return false
	}

	return snapshot.ProfilePictureURL != snapshot.Before.ProfilePictureURL
}

2023-01-24 10:49 UTC, ice-myles commented on tasks/users_source.go
> +	// 1. Claim your nickname.
Remove please these comments or at least you can write the task with index.
Because when you check 
```
if u.isNicknameClaimed(snapshot) {
```
is it clear that you are checking claim you nickname task.

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +		// Remove pending flag from database if next task is ready.
Remove please this comment, it's obsolete. Logic is clear from the code.

2023-01-24 10:49 UTC, ice-myles commented on tasks/tasks_complete.go
> +	return errors.Wrapf(r.sendCompleteTask(ctx, now, task, done), "failed to send completed task for task %v and userID:%v", task.Name, task.UserID)
Is it right that if we didn't send the complete task message, we should revert this task and mark it as uncompleted in the database? @ice-ares

2023-01-24 11:10 UTC, ice-nestor commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before != nil)
https://github.com/ice-blockchain/santa/pull/8#discussion_r1083621471 ?

2023-01-24 11:15 UTC, ice-myles commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before != nil)
Modify is when
snapshot.Before != nil AND
snapshot.User != nil

If snapshot.Before != nil only it can be next case:
snapshot.Before != nil AND snapshot.User == nil and this is user removing.

If this isNicknameClaimed check will have never got snapshot.User == nil, so I would not complicate the code.

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		// Remove pending flag from database if next task is ready.
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/users_source.go
> +	// 1. Claim your nickname.
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/users_source.go
> +	return (!u.defaultProfilePictureNameRegex.MatchString(snapshot.ProfilePictureURL)) && (snapshot.Before == nil || hadDefaultPictureBefore)
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/users_source.go
> +	return snapshot.Username != "" && (snapshot.Before != nil)
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	return errors.Wrapf(r.sendMsg(ctx, completedTask, completedTask.UserID, r.cfg.MessageBroker.Topics[0].Name),
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	nextAchievedTasks := make([]*AchievedTask, 0, 1)
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +		// Send reward message to freezer.
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	// Append sequentially each next task that is achieved, if next sequential isn't found then stop
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +// getPreviousNextAchievedTasks returns previous tasks before current task, next tasks that come after current task and are achieved
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/tasks_complete.go
> +	if done := isLastTaskDone(achievedTasks); done { // No need to continue if last task is done.
done

2023-01-24 11:18 UTC, ice-nestor commented on tasks/progress.go
> +		return 0, errors.Wrapf(storage.ErrNotFound, "no response from user progress update for userID:%v", userID)
changed

2023-01-24 11:18 UTC, ice-nestor commented on tasks/progress.go
> +	// Normally update is sent to progress topic here.
done

2023-01-24 11:19 UTC, ice-nestor commented on tasks/progress.go
> +	// Normally update is sent to progress topic here.
done

2023-01-24 11:19 UTC, ice-nestor commented on tasks/contract.go
> +		_msgpack   struct{}   `msgpack:",asArray"`
done

2023-01-25 08:51 UTC, ice-cronus approved these changes

2023-03-22 21:47 UTC, closed without merging